# Generated by Django 5.1.4 on 2025-06-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0016_remove_student_uses_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(default='building', max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
    ]
