# Generated by Django 5.2.1 on 2025-05-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
