# Generated by Django 5.1.4 on 2025-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_guest_studentnumber_rsvp_guest_studentnumber'),
        ('events', '0013_archivedevents_event_capacity_event_title_and_more'),
    ]

    operations = [
    ]
