# Generated by Django 5.1.4 on 2025-03-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_alter_student_stud_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Action',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.admin')),
            ],
        ),
    ]
