# Generated by Django 5.1.4 on 2025-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_action',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
