# Generated by Django 5.2.1 on 2025-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_student_stud_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uses_bus',
            field=models.BooleanField(default=False),
        ),
    ]
