# Generated by Django 5.1.4 on 2025-06-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_student_uses_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uses_bus',
        ),
    ]
