# Generated by Django 5.2.1 on 2025-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_bus_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_stats',
            name='actual_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulecode',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
