# Generated by Django 5.1.4 on 2025-06-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_bus_stats_actual_arrival_time_and_more'),
        ('login', '0016_remove_student_uses_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_stats',
            name='actual_arrival_time',
        ),
        migrations.RemoveField(
            model_name='schedulecode',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='bus_stats',
            name='student_id',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
            preserve_default=False,
        ),
    ]
