# Generated by Django 5.1.4 on 2025-06-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_bus_stats_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleCode',
            new_name='Route',
        ),
    ]
